apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # This reads the environment variable set by Render
    url: http://${PROMETHEUS_URL}:9090
    isDefault: true
    editable: true
